alter table public.app_state
  add column if not exists gym_name text;

create table if not exists public.gym_place (
  id bigint generated by default as identity primary key,
  name text not null,
  latitude double precision not null,
  longitude double precision not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists gym_place_latitude_idx on public.gym_place (latitude);
create index if not exists gym_place_longitude_idx on public.gym_place (longitude);

alter table public.gym_place disable row level security;
grant all on table public.gym_place to anon;
grant all on table public.gym_place to authenticated;
grant all on sequence public.gym_place_id_seq to anon;
grant all on sequence public.gym_place_id_seq to authenticated;
