create table if not exists public.exercise_performance_index (
  id bigint generated by default as identity primary key,
  workout_id bigint not null references public.workout(id) on delete cascade,
  exercise_id bigint not null references public.exercise(id) on delete cascade,
  total_volume_pr numeric not null default 0,
  best_set_e1rm_pr numeric not null default 0,
  total_volume_pr_date date,
  best_set_e1rm_pr_date date,
  rep_prs jsonb not null default '{}'::jsonb,
  rep_pr_dates jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),
  unique (exercise_id)
);

create index if not exists exercise_performance_index_workout_id_idx
  on public.exercise_performance_index(workout_id);

create index if not exists exercise_performance_index_exercise_id_idx
  on public.exercise_performance_index(exercise_id);
