create table if not exists public.exercise_daily_snapshot (
  id bigint generated by default as identity primary key,
  exercise_id bigint not null references public.exercise(id) on update cascade on delete cascade,
  snapshot_date date not null default ((now() at time zone 'utc')::date),
  snapshot_state jsonb not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (exercise_id, snapshot_date)
);

create index if not exists idx_exercise_daily_snapshot_exercise_id
  on public.exercise_daily_snapshot (exercise_id);

create index if not exists idx_exercise_daily_snapshot_snapshot_date
  on public.exercise_daily_snapshot (snapshot_date desc);

alter table public.exercise_daily_snapshot enable row level security;

grant all on table public.exercise_daily_snapshot to anon;
grant all on table public.exercise_daily_snapshot to authenticated;
